/*This do file processes the AllStatesNov2016.dta which was generated by Amy and 
appended by Rebecca to include KY. */ 


clear all
use AllStatesNov2016.dta
		keep County Trump Clinton TotVotes statefips cntycode uniqfips pctTrump r_T_C
		replace pctTrump= (Trump/TotVotes) *100
		replace r_T_C= Trump/Clinton
		destring uniqfips  cntycode, replace
		replace uniqfips= uniqfips/10
save AllStates.dta, replace
clear all
